version: '3.8'

services:
  db_postgres:
    container_name: db_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:13.11-bullseye
